"""add likes to posts

Revision ID: 8e980ccce9db
Revises: a14b4ba8a6d2
Create Date: 2026-06-05 17:25:40.545834

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8e980ccce9db"
down_revision: Union[str, Sequence[str], None] = "a14b4ba8a6d2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "posts", sa.Column("likes", sa.Integer(), server_default="0", nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("posts", "likes")
    # ### end Alembic commands ###
