name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/fastapi-blog
            git pull
            /home/caneroren/.local/bin/uv sync
            /home/caneroren/.local/bin/uv run alembic upgrade head
            sudo systemctl restart fastapi-blog
